// Generated by gencpp from file vaafo_msgs/AVResetRequest.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_AVRESETREQUEST_H
#define VAAFO_MSGS_MESSAGE_AVRESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vaafo_msgs/CarInfo.h>

namespace vaafo_msgs
{
template <class ContainerAllocator>
struct AVResetRequest_
{
  typedef AVResetRequest_<ContainerAllocator> Type;

  AVResetRequest_()
    : reset(false)
    , carinfo_()  {
    }
  AVResetRequest_(const ContainerAllocator& _alloc)
    : reset(false)
    , carinfo_(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_type;
  _reset_type reset;

   typedef  ::vaafo_msgs::CarInfo_<ContainerAllocator>  _carinfo__type;
  _carinfo__type carinfo_;





  typedef boost::shared_ptr< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AVResetRequest_

typedef ::vaafo_msgs::AVResetRequest_<std::allocator<void> > AVResetRequest;

typedef boost::shared_ptr< ::vaafo_msgs::AVResetRequest > AVResetRequestPtr;
typedef boost::shared_ptr< ::vaafo_msgs::AVResetRequest const> AVResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::AVResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::AVResetRequest_<ContainerAllocator1> & lhs, const ::vaafo_msgs::AVResetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reset == rhs.reset &&
    lhs.carinfo_ == rhs.carinfo_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::AVResetRequest_<ContainerAllocator1> & lhs, const ::vaafo_msgs::AVResetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39aa934f442d132c812b5a2c005712ab";
  }

  static const char* value(const ::vaafo_msgs::AVResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39aa934f442d132cULL;
  static const uint64_t static_value2 = 0x812b5a2c005712abULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/AVResetRequest";
  }

  static const char* value(const ::vaafo_msgs::AVResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset   # whether reset is sent\n"
"vaafo_msgs/CarInfo carinfo_ #send reset status of driver\n"
"\n"
"================================================================================\n"
"MSG: vaafo_msgs/CarInfo\n"
"std_msgs/Header header\n"
"int32 lane_id\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist acceleration\n"
"geometry_msgs/Point s_d\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::vaafo_msgs::AVResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset);
      stream.next(m.carinfo_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AVResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::AVResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::AVResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
    s << indent << "carinfo_: ";
    s << std::endl;
    Printer< ::vaafo_msgs::CarInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.carinfo_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_AVRESETREQUEST_H
