// Generated by gencpp from file vaafo_msgs/AVResetResponse.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_AVRESETRESPONSE_H
#define VAAFO_MSGS_MESSAGE_AVRESETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vaafo_msgs
{
template <class ContainerAllocator>
struct AVResetResponse_
{
  typedef AVResetResponse_<ContainerAllocator> Type;

  AVResetResponse_()
    : res(false)  {
    }
  AVResetResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AVResetResponse_

typedef ::vaafo_msgs::AVResetResponse_<std::allocator<void> > AVResetResponse;

typedef boost::shared_ptr< ::vaafo_msgs::AVResetResponse > AVResetResponsePtr;
typedef boost::shared_ptr< ::vaafo_msgs::AVResetResponse const> AVResetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::AVResetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::AVResetResponse_<ContainerAllocator1> & lhs, const ::vaafo_msgs::AVResetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::AVResetResponse_<ContainerAllocator1> & lhs, const ::vaafo_msgs::AVResetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::vaafo_msgs::AVResetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/AVResetResponse";
  }

  static const char* value(const ::vaafo_msgs::AVResetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  res    # result of triggered service\n"
"\n"
"\n"
;
  }

  static const char* value(const ::vaafo_msgs::AVResetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AVResetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::AVResetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::AVResetResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_AVRESETRESPONSE_H
