// Generated by gencpp from file vaafo_msgs/CMRemoteResponse.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_CMREMOTERESPONSE_H
#define VAAFO_MSGS_MESSAGE_CMREMOTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vaafo_msgs
{
template <class ContainerAllocator>
struct CMRemoteResponse_
{
  typedef CMRemoteResponse_<ContainerAllocator> Type;

  CMRemoteResponse_()
    : res(0)
    , msg()  {
    }
  CMRemoteResponse_(const ContainerAllocator& _alloc)
    : res(0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CMRemoteResponse_

typedef ::vaafo_msgs::CMRemoteResponse_<std::allocator<void> > CMRemoteResponse;

typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteResponse > CMRemoteResponsePtr;
typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteResponse const> CMRemoteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator1> & lhs, const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator1> & lhs, const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf6b5d22125b6caef41ccf14f7c3348";
  }

  static const char* value(const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf6b5d22125b6caULL;
  static const uint64_t static_value2 = 0xef41ccf14f7c3348ULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/CMRemoteResponse";
  }

  static const char* value(const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  res    # result of triggered service\n"
"string msg    # informational, e.g. for error messages\n"
"\n"
;
  }

  static const char* value(const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CMRemoteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::CMRemoteResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_CMREMOTERESPONSE_H
