// Generated by gencpp from file vaafo_msgs/SensorObjectList.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_SENSOROBJECTLIST_H
#define VAAFO_MSGS_MESSAGE_SENSOROBJECTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vaafo_msgs/SensorObjectInfo.h>

namespace vaafo_msgs
{
template <class ContainerAllocator>
struct SensorObjectList_
{
  typedef SensorObjectList_<ContainerAllocator> Type;

  SensorObjectList_()
    : header()
    , objects()  {
    }
  SensorObjectList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vaafo_msgs::SensorObjectInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vaafo_msgs::SensorObjectInfo_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> const> ConstPtr;

}; // struct SensorObjectList_

typedef ::vaafo_msgs::SensorObjectList_<std::allocator<void> > SensorObjectList;

typedef boost::shared_ptr< ::vaafo_msgs::SensorObjectList > SensorObjectListPtr;
typedef boost::shared_ptr< ::vaafo_msgs::SensorObjectList const> SensorObjectListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::SensorObjectList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::SensorObjectList_<ContainerAllocator1> & lhs, const ::vaafo_msgs::SensorObjectList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::SensorObjectList_<ContainerAllocator1> & lhs, const ::vaafo_msgs::SensorObjectList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c86b06d42ea813ae9a4aa2b93685199";
  }

  static const char* value(const ::vaafo_msgs::SensorObjectList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c86b06d42ea813aULL;
  static const uint64_t static_value2 = 0xe9a4aa2b93685199ULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/SensorObjectList";
  }

  static const char* value(const ::vaafo_msgs::SensorObjectList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"SensorObjectInfo[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vaafo_msgs/SensorObjectInfo\n"
"std_msgs/Header header\n"
"int8 traffic_id\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist velocity\n"
"geometry_msgs/Twist acceleration\n"
"geometry_msgs/Point dimension\n"
"geometry_msgs/Twist rel_velocity\n"
"float64 rel_Ref_dis\n"
"float64 rel_Near_dis\n"
"float64 rel_Ref_azimut\n"
"float64 rel_Near_azimut\n"
"float64 rel_Ref_orientation\n"
"float64 rel_Ref_vel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vaafo_msgs::SensorObjectList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorObjectList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::SensorObjectList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::SensorObjectList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vaafo_msgs::SensorObjectInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_SENSOROBJECTLIST_H
