// Generated by gencpp from file vaafo_msgs/State.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_STATE_H
#define VAAFO_MSGS_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>
#include <vaafo_msgs/CarInfo.h>

namespace vaafo_msgs
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : header()
    , state_id(0)
    , state()
    , target()  {
    }
  State_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state_id(0)
    , state(_alloc)
    , target(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _state_id_type;
  _state_id_type state_id;

   typedef  ::std_msgs::String_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::vaafo_msgs::CarInfo_<ContainerAllocator>  _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::vaafo_msgs::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::vaafo_msgs::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::vaafo_msgs::State > StatePtr;
typedef boost::shared_ptr< ::vaafo_msgs::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::State_<ContainerAllocator1> & lhs, const ::vaafo_msgs::State_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.state_id == rhs.state_id &&
    lhs.state == rhs.state &&
    lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::State_<ContainerAllocator1> & lhs, const ::vaafo_msgs::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::State_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::State_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3e858bcb52021813bb91c3e8bb23dab";
  }

  static const char* value(const ::vaafo_msgs::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3e858bcb5202181ULL;
  static const uint64_t static_value2 = 0x3bb91c3e8bb23dabULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/State";
  }

  static const char* value(const ::vaafo_msgs::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int8 state_id\n"
"std_msgs/String state\n"
"CarInfo target\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: vaafo_msgs/CarInfo\n"
"std_msgs/Header header\n"
"int32 lane_id\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist acceleration\n"
"geometry_msgs/Point s_d\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::vaafo_msgs::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state_id);
      stream.next(m.state);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::State_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state_id);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::vaafo_msgs::CarInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_STATE_H
