// Generated by gencpp from file vaafo_msgs/AVReset.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_AVRESET_H
#define VAAFO_MSGS_MESSAGE_AVRESET_H

#include <ros/service_traits.h>


#include <vaafo_msgs/AVResetRequest.h>
#include <vaafo_msgs/AVResetResponse.h>


namespace vaafo_msgs
{

struct AVReset
{

typedef AVResetRequest Request;
typedef AVResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AVReset
} // namespace vaafo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vaafo_msgs::AVReset > {
  static const char* value()
  {
    return "d0a29e7e47f617413ad877c4401f3a68";
  }

  static const char* value(const ::vaafo_msgs::AVReset&) { return value(); }
};

template<>
struct DataType< ::vaafo_msgs::AVReset > {
  static const char* value()
  {
    return "vaafo_msgs/AVReset";
  }

  static const char* value(const ::vaafo_msgs::AVReset&) { return value(); }
};


// service_traits::MD5Sum< ::vaafo_msgs::AVResetRequest> should match
// service_traits::MD5Sum< ::vaafo_msgs::AVReset >
template<>
struct MD5Sum< ::vaafo_msgs::AVResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vaafo_msgs::AVReset >::value();
  }
  static const char* value(const ::vaafo_msgs::AVResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vaafo_msgs::AVResetRequest> should match
// service_traits::DataType< ::vaafo_msgs::AVReset >
template<>
struct DataType< ::vaafo_msgs::AVResetRequest>
{
  static const char* value()
  {
    return DataType< ::vaafo_msgs::AVReset >::value();
  }
  static const char* value(const ::vaafo_msgs::AVResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vaafo_msgs::AVResetResponse> should match
// service_traits::MD5Sum< ::vaafo_msgs::AVReset >
template<>
struct MD5Sum< ::vaafo_msgs::AVResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vaafo_msgs::AVReset >::value();
  }
  static const char* value(const ::vaafo_msgs::AVResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vaafo_msgs::AVResetResponse> should match
// service_traits::DataType< ::vaafo_msgs::AVReset >
template<>
struct DataType< ::vaafo_msgs::AVResetResponse>
{
  static const char* value()
  {
    return DataType< ::vaafo_msgs::AVReset >::value();
  }
  static const char* value(const ::vaafo_msgs::AVResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_AVRESET_H
