// Generated by gencpp from file vaafo_msgs/CarInfo.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_CARINFO_H
#define VAAFO_MSGS_MESSAGE_CARINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Point.h>

namespace vaafo_msgs
{
template <class ContainerAllocator>
struct CarInfo_
{
  typedef CarInfo_<ContainerAllocator> Type;

  CarInfo_()
    : header()
    , lane_id(0)
    , twist()
    , pose()
    , acceleration()
    , s_d()  {
    }
  CarInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lane_id(0)
    , twist(_alloc)
    , pose(_alloc)
    , acceleration(_alloc)
    , s_d(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _lane_id_type;
  _lane_id_type lane_id;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _s_d_type;
  _s_d_type s_d;





  typedef boost::shared_ptr< ::vaafo_msgs::CarInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::CarInfo_<ContainerAllocator> const> ConstPtr;

}; // struct CarInfo_

typedef ::vaafo_msgs::CarInfo_<std::allocator<void> > CarInfo;

typedef boost::shared_ptr< ::vaafo_msgs::CarInfo > CarInfoPtr;
typedef boost::shared_ptr< ::vaafo_msgs::CarInfo const> CarInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::CarInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::CarInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::CarInfo_<ContainerAllocator1> & lhs, const ::vaafo_msgs::CarInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lane_id == rhs.lane_id &&
    lhs.twist == rhs.twist &&
    lhs.pose == rhs.pose &&
    lhs.acceleration == rhs.acceleration &&
    lhs.s_d == rhs.s_d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::CarInfo_<ContainerAllocator1> & lhs, const ::vaafo_msgs::CarInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::CarInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::CarInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::CarInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c2ff4da63cd46f1391da42a7b9eec92";
  }

  static const char* value(const ::vaafo_msgs::CarInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c2ff4da63cd46f1ULL;
  static const uint64_t static_value2 = 0x391da42a7b9eec92ULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/CarInfo";
  }

  static const char* value(const ::vaafo_msgs::CarInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 lane_id\n"
"geometry_msgs/Twist twist\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist acceleration\n"
"geometry_msgs/Point s_d\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::vaafo_msgs::CarInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lane_id);
      stream.next(m.twist);
      stream.next(m.pose);
      stream.next(m.acceleration);
      stream.next(m.s_d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::CarInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::CarInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lane_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lane_id);
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "s_d: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.s_d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_CARINFO_H
