// Generated by gencpp from file vaafo_msgs/CMRemoteRequest.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_CMREMOTEREQUEST_H
#define VAAFO_MSGS_MESSAGE_CMREMOTEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vaafo_msgs
{
template <class ContainerAllocator>
struct CMRemoteRequest_
{
  typedef CMRemoteRequest_<ContainerAllocator> Type;

  CMRemoteRequest_()
    : type()
    , msg()
    , data()  {
    }
  CMRemoteRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , msg(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CMRemoteRequest_

typedef ::vaafo_msgs::CMRemoteRequest_<std::allocator<void> > CMRemoteRequest;

typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteRequest > CMRemoteRequestPtr;
typedef boost::shared_ptr< ::vaafo_msgs::CMRemoteRequest const> CMRemoteRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator1> & lhs, const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.msg == rhs.msg &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator1> & lhs, const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a20fcbf285ac8d5dda1e13b8bc92d134";
  }

  static const char* value(const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa20fcbf285ac8d5dULL;
  static const uint64_t static_value2 = 0xda1e13b8bc92d134ULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/CMRemoteRequest";
  }

  static const char* value(const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type   # general type of command\n"
"string msg    # message to be evaluated\n"
"string data   # additional data, e.g. command arguments, ...\n"
;
  }

  static const char* value(const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.msg);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CMRemoteRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::CMRemoteRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_CMREMOTEREQUEST_H
