// Generated by gencpp from file vaafo_msgs/CMRemote.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_CMREMOTE_H
#define VAAFO_MSGS_MESSAGE_CMREMOTE_H

#include <ros/service_traits.h>


#include <vaafo_msgs/CMRemoteRequest.h>
#include <vaafo_msgs/CMRemoteResponse.h>


namespace vaafo_msgs
{

struct CMRemote
{

typedef CMRemoteRequest Request;
typedef CMRemoteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CMRemote
} // namespace vaafo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vaafo_msgs::CMRemote > {
  static const char* value()
  {
    return "1d9ce7b684aec19fba170323f6c05b62";
  }

  static const char* value(const ::vaafo_msgs::CMRemote&) { return value(); }
};

template<>
struct DataType< ::vaafo_msgs::CMRemote > {
  static const char* value()
  {
    return "vaafo_msgs/CMRemote";
  }

  static const char* value(const ::vaafo_msgs::CMRemote&) { return value(); }
};


// service_traits::MD5Sum< ::vaafo_msgs::CMRemoteRequest> should match
// service_traits::MD5Sum< ::vaafo_msgs::CMRemote >
template<>
struct MD5Sum< ::vaafo_msgs::CMRemoteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vaafo_msgs::CMRemote >::value();
  }
  static const char* value(const ::vaafo_msgs::CMRemoteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vaafo_msgs::CMRemoteRequest> should match
// service_traits::DataType< ::vaafo_msgs::CMRemote >
template<>
struct DataType< ::vaafo_msgs::CMRemoteRequest>
{
  static const char* value()
  {
    return DataType< ::vaafo_msgs::CMRemote >::value();
  }
  static const char* value(const ::vaafo_msgs::CMRemoteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vaafo_msgs::CMRemoteResponse> should match
// service_traits::MD5Sum< ::vaafo_msgs::CMRemote >
template<>
struct MD5Sum< ::vaafo_msgs::CMRemoteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vaafo_msgs::CMRemote >::value();
  }
  static const char* value(const ::vaafo_msgs::CMRemoteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vaafo_msgs::CMRemoteResponse> should match
// service_traits::DataType< ::vaafo_msgs::CMRemote >
template<>
struct DataType< ::vaafo_msgs::CMRemoteResponse>
{
  static const char* value()
  {
    return DataType< ::vaafo_msgs::CMRemote >::value();
  }
  static const char* value(const ::vaafo_msgs::CMRemoteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_CMREMOTE_H
