// Generated by gencpp from file vaafo_msgs/ControlSeq.msg
// DO NOT EDIT!


#ifndef VAAFO_MSGS_MESSAGE_CONTROLSEQ_H
#define VAAFO_MSGS_MESSAGE_CONTROLSEQ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vaafo_msgs/Control.h>

namespace vaafo_msgs
{
template <class ContainerAllocator>
struct ControlSeq_
{
  typedef ControlSeq_<ContainerAllocator> Type;

  ControlSeq_()
    : header()
    , contro_seq()  {
    }
  ControlSeq_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , contro_seq(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vaafo_msgs::Control_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vaafo_msgs::Control_<ContainerAllocator> >::other >  _contro_seq_type;
  _contro_seq_type contro_seq;





  typedef boost::shared_ptr< ::vaafo_msgs::ControlSeq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vaafo_msgs::ControlSeq_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSeq_

typedef ::vaafo_msgs::ControlSeq_<std::allocator<void> > ControlSeq;

typedef boost::shared_ptr< ::vaafo_msgs::ControlSeq > ControlSeqPtr;
typedef boost::shared_ptr< ::vaafo_msgs::ControlSeq const> ControlSeqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vaafo_msgs::ControlSeq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vaafo_msgs::ControlSeq_<ContainerAllocator1> & lhs, const ::vaafo_msgs::ControlSeq_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.contro_seq == rhs.contro_seq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vaafo_msgs::ControlSeq_<ContainerAllocator1> & lhs, const ::vaafo_msgs::ControlSeq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vaafo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vaafo_msgs::ControlSeq_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vaafo_msgs::ControlSeq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vaafo_msgs::ControlSeq_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbe87f7a69e1df9db1b708eea0b009c6";
  }

  static const char* value(const ::vaafo_msgs::ControlSeq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbe87f7a69e1df9dULL;
  static const uint64_t static_value2 = 0xb1b708eea0b009c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vaafo_msgs/ControlSeq";
  }

  static const char* value(const ::vaafo_msgs::ControlSeq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Control[] contro_seq\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vaafo_msgs/Control\n"
"std_msgs/Header header\n"
"std_msgs/Float64 steering_ang\n"
"std_msgs/Float64 accel\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::vaafo_msgs::ControlSeq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.contro_seq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSeq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vaafo_msgs::ControlSeq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vaafo_msgs::ControlSeq_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "contro_seq[]" << std::endl;
    for (size_t i = 0; i < v.contro_seq.size(); ++i)
    {
      s << indent << "  contro_seq[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vaafo_msgs::Control_<ContainerAllocator> >::stream(s, indent + "    ", v.contro_seq[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAAFO_MSGS_MESSAGE_CONTROLSEQ_H
